"""empty message

Revision ID: 156e63e14620
Revises: 296c95c30c57
Create Date: 2024-12-14 03:15:18.980081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156e63e14620'
down_revision = '296c95c30c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
