"""empty message

Revision ID: 296c95c30c57
Revises: ebe6a6df6a5c
Create Date: 2024-12-14 03:00:05.836910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296c95c30c57'
down_revision = 'ebe6a6df6a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_id_seller_fkey', type_='foreignkey')
        batch_op.drop_column('id_seller')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_seller', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('post_id_seller_fkey', 'user', ['id_seller'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
