"""empty message

Revision ID: 388d81cb13fb
Revises: 51e4ee53d100
Create Date: 2025-03-01 17:03:38.467370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '388d81cb13fb'
down_revision = '51e4ee53d100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('papers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('picture', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id_author', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['user.id'], name='papers_id_author_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='papers_pkey')
    )
    op.drop_table('blog')
    # ### end Alembic commands ###
