"""empty message

Revision ID: 38c1a3a6e2fe
Revises: 5e5da7f2dc5c
Create Date: 2024-12-16 22:25:19.259440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c1a3a6e2fe'
down_revision = '5e5da7f2dc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=200), nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
