"""empty message

Revision ID: 727f1b65cdb6
Revises: 156e63e14620
Create Date: 2024-12-14 18:29:50.006129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727f1b65cdb6'
down_revision = '156e63e14620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_seller', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['id_seller'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_seller')

    # ### end Alembic commands ###
